### ISSUE TITLE
Error with sync library page empty

### ISSUE THREAD

**Issue by johnvick** [CyferShepard/Jellystat#38] opened 2023-05-31 09:16 UTC
Using v 1.0.4.2 - thanks, software looks promising.

Trying to sync see this in Docker log:

Failed to fetch releases for Jellystat: 403 error making request get https://api.github.com/repos/cyfershepard/Jellystat/contents/package.json: "rate limit exceeded"

(maybe not relevant, I don't know)

And the sync log:

Syncing... 1/3
Beginning Library Item Sync
at jf_library_items_mapping (/app/backend/models/jf_library_items.js:45:79: Error: TypeError: Cannot read properties of undefined (reading '2d042b1a6c0c4b35d995c0758f84c654')
Syncing... 2/3
Beginning Seasons and Episode sync
Seasons: 0 Rows Inserted. 0 Rows Updated.
0 Seasons Removed.
Episodes: 0 Rows Inserted. 0 Rows Updated.
0 Episodes Removed.
Sync Complete
Syncing... 3/4
Beginning File Info Sync
0 Item Info inserted.
0 Item Info Removed.
0 Episodes Info inserted.
0 Episodes Info Removed.
Info Sync Complete
Syncing... 4/4
Removing Orphaned FileInfo/Episode/Season Records
Orphaned FileInfo/Episode/Season Removed.
Sync Complete

My Docker-compose script via Portainer is pretty faithful to your example.

The homepage shows currently playing OK but the recently added is outdated.

**Comment by CyferShepard** [comment] 2023-05-31 09:19
Hi @johnvick , thanks for the logs, this seems to be a widespread issue, with these logs it makes things easier and I'm currently looking into it

**Comment by CyferShepard** [comment] 2023-05-31 10:10
@johnvick can you pull the latest build 1.0.4.3 and let me know if that helps

**Comment by Zegorax** [comment] 2023-05-31 12:40
I just tested with 1.0.4.3 and the problem seems to still be there (same error message)

**Comment by CyferShepard** [comment] 2023-05-31 12:45
Thanks @Zegorax , im still testing a new change at the moment but i have made some progress. @johnvick  since this ended up being a duplicate of #37 Im going to close this issue and continue there to prevent any confusion

**Closed by CyferShepard** 2023-05-31 12:45 UTC
